export default {
  genres: [
    "pop",
    "dance pop",
    "rap",
    "rock",
    "pop rap",
    "latin",
    "hip hop",
    "trap latino",
    "trap",
    "modern rock",
    "reggaeton",
    "edm",
    "pop dance",
    "post-teen pop",
    "pop rock",
    "classic rock",
    "latin pop",
    "electropop",
    "tropical house",
    "mellow gold",
    "r&b",
    "soft rock",
    "regional mexican",
    "permanent wave",
    "album rock",
    "k-pop",
    "alternative metal",
    "southern hip hop",
    "indie pop",
    "canadian pop",
    "contemporary country",
    "corrido",
    "uk pop",
    "urban contemporary",
    "melodic rap",
    "electro house",
    "country",
    "alternative rock",
    "hard rock",
    "nu metal",
    "alt z",
    "nuevo regional mexicano",
    "neo mellow",
    "rock en espanol",
    "gangster rap",
    "latin hip hop",
    "modern alternative rock",
    "country road",
    "underground hip hop",
    "tropical",
    "folk rock",
    "chicago rap",
    "new wave pop",
    "german hip hop",
    "atl hip hop",
    "country rock",
    "adult standards",
    "french hip hop",
    "k-pop boy group",
    "canadian hip hop",
    "desi pop",
    "soul",
    "indie poptimism",
    "europop",
    "alternative r&b",
    "pop urbaine",
    "art rock",
    "latin alternative",
    "latin rock",
    "mexican pop",
    "reggaeton colombiano",
    "house",
    "funk carioca",
    "j-pop",
    "toronto rap",
    "sertanejo universitario",
    "hip pop",
    "indie folk",
    "stomp and holler",
    "norteno",
    "viral pop",
    "metal",
    "neo soul",
    "indie rock",
    "latin arena pop",
    "filmi",
    "post-grunge",
    "spanish pop",
    "francoton",
    "indie soul",
    "new wave",
    "sertanejo",
    "sertanejo pop",
    "art pop",
    "reggaeton flow",
    "funk",
    "pop punk",
    "colombian pop",
    "modern bollywood",
    "emo rap",
    "blues rock",
    "lgbtq+ hip hop",
    "quiet storm",
    "sierreno",
    "conscious hip hop",
    "singer-songwriter",
    "rap francais",
    "indietronica",
    "slap house",
    "pop edm",
    "italian pop",
    "uk dance",
    "boy band",
    "motown",
    "miami hip hop",
    "new romantic",
    "east coast hip hop",
    "german pop",
    "sad rap",
    "pop r&b",
    "disco",
    "progressive house",
    "banda",
    "dark trap",
    "canadian contemporary r&b",
    "rap metal",
    "australian pop",
    "psychedelic rock",
    "metropopolis",
    "glam rock",
    "folk",
    "italian hip hop",
    "puerto rican pop",
    "escape room",
    "sleep",
    "vapor trap",
    "swedish pop",
    "russian hip hop",
    "bedroom pop",
    "roots rock",
    "ranchera",
    "indie r&b",
    "modern country rock",
    "k-pop girl group",
    "punk",
    "hoerspiel",
    "electronica",
    "ccm",
    "piano rock",
    "progressive electro house",
    "brill building pop",
    "argentine rock",
    "metalcore",
    "sad lo-fi",
    "mpb",
    "alternative hip hop",
    "corridos tumbados",
    "chill r&b",
    "christian music",
    "alternative dance",
    "heartland rock",
    "uk hip hop",
    "hardcore hip hop",
    "anime",
    "indonesian pop",
    "turkish pop",
    "vocal jazz",
    "talent show",
    "trap argentino",
    "west coast rap",
    "worship",
    "rap rock",
    "new french touch",
    "social media pop",
    "pagode",
    "big room",
    "australian hip hop",
    "brooklyn drill",
    "lo-fi beats",
    "urbano espanol",
    "hollywood",
    "polish hip hop",
    "italian adult pop",
    "dance rock",
    "mexican hip hop",
    "otacore",
    "yacht rock",
    "detroit hip hop",
    "sufi",
    "classical",
    "country pop",
    "folk-pop",
    "french pop",
    "turkish trap pop",
    "new americana",
    "lounge",
    "pop nacional",
    "soundtrack",
    "world worship",
    "dirty south rap",
    "opm",
    "cali rap",
    "christian alternative rock",
    "forro",
    "mariachi",
    "synthpop",
    "new rave",
    "glam metal",
    "melodic metalcore",
    "dutch pop",
    "british invasion",
    "j-rock",
    "rock-and-roll",
    "cantautor",
    "classic soul",
    "brazilian rock",
    "beatlesque",
    "brostep",
    "eurodance",
    "funk metal",
    "british soul",
    "garage rock",
    "bolero",
    "trap queen",
    "grupera",
    "argentine hip hop",
    "aesthetic rap",
    "indiecoustica",
    "viral rap",
    "new jack swing",
    "dutch hip hop",
    "russian pop",
    "rap conscient",
    "electronic trap",
    "nova mpb",
    "bubblegum pop",
    "grunge",
    "mexican rock",
    "melancholia",
    "emo",
    "north carolina hip hop",
    "deep house",
    "acoustic pop",
    "brazilian hip hop",
    "vapor soul",
    "funk ostentacao",
    "salsa",
    "texas country",
    "queens hip hop",
    "trance",
    "bachata",
    "symphonic rock",
    "girl group",
    "dfw rap",
    "outlaw country",
    "german rock",
    "mandopop",
    "nyc rap",
    "punjabi pop",
    "dream pop",
    "country dawn",
    "modern blues rock",
    "funk rock",
    "screamo",
    "progressive rock",
    "lilith",
    "new orleans rap",
    "german trap",
    "g funk",
    "chanson",
    "show tunes",
    "australian dance",
    "comic",
    "pop soul",
    "turkish hip hop",
    "dream smp",
    "australian rock",
    "britpop",
    "chillhop",
    "reggae fusion",
    "video game music",
    "polish trap",
    "memphis hip hop",
    "philly rap",
    "trap triste",
    "power metal",
    "turkish trap",
    "rain",
    "reggae",
    "russian trap",
    "florida rap",
    "anime rock",
    "rockabilly",
    "kleine hoerspiel",
    "easy listening",
    "merseybeat",
    "j-poprock",
    "german dance",
    "la indie",
    "freak folk",
    "dutch edm",
    "ohio hip hop",
    "french indie pop",
    "dutch rap pop",
    "neo-classical",
    "downtempo",
    "lo-fi product",
    "meme rap",
    "compositional ambient",
    "industrial metal",
    "bubblegum dance",
    "candy pop",
    "chamber pop",
    "bossa nova",
    "latin viral pop",
    "indie garage rock",
    "adoracao",
    "deep groove house",
    "trap brasileiro",
    "plugg",
    "afropop",
    "bass trap",
    "gruperas inmortales",
    "chillwave",
    "baroque pop",
    "children's music",
    "german techno",
    "anthem worship",
    "atl trap",
    "norwegian pop",
    "indie rock italiano",
    "indie anthem-folk",
    "disco house",
    "dancehall",
    "skate punk",
    "cumbia pop",
    "nigerian pop",
    "danish pop",
    "canadian rock",
    "southern soul",
    "nueva cancion",
    "italian indie pop",
    "modern indie pop",
    "deep tropical house",
    "trap italiana",
    "barbadian pop",
    "japanese teen pop",
    "brazilian edm",
    "gauze pop",
    "deep regional mexican",
    "rock nacional",
    "classic italian pop",
    "perreo",
    "pittsburgh rap",
    "neo-psychedelic",
    "rap latina",
    "old school thrash",
    "sophisti-pop",
    "roots reggae",
    "dominican pop",
    "indie pop rap",
    "spanish pop rock",
    "gaming edm",
    "background music",
    "pixie",
    "scorecore",
    "vapor twitch",
    "pop venezolano",
    "turkish rock",
    "spanish hip hop",
    "jazz funk",
    "trap soul",
    "latin worship",
    "hip house",
    "taiwan pop",
    "funk paulista",
    "uk contemporary r&b",
    "brazilian gospel",
    "tennessee hip hop",
    "korean pop",
    "baton rouge rap",
    "pop argentino",
    "electric blues",
    "desi hip hop",
    "cumbia villera",
    "partyschlager",
    "jazz",
    "redneck",
    "rap calme",
    "christian rock",
    "deep german hip hop",
    "grime",
    "instrumental lullaby",
    "thrash metal",
    "mexican indie",
    "la pop",
    "pop flamenco",
    "tamil pop",
    "shimmer pop",
    "nz pop",
    "rock nacional brasileiro",
    "latin christian",
    "houston rap",
    "trip hop",
    "rap marseille",
    "axe",
    "filter house",
    "post-disco",
    "future bass",
    "southern rock",
    "post-screamo",
    "dmv rap",
    "samba",
    "nu jazz",
    "lo-fi jazzhop",
    "shiver pop",
    "swedish hip hop",
    "ska argentino",
    "socal pop punk",
    "glitchcore",
    "industrial rock",
    "c-pop",
    "focus beats",
    "madchester",
    "cancion melodica",
    "night drive phonk",
    "dutch rock",
    "korean r&b",
    "afrofuturism",
    "australian indie",
    "rap conciencia",
    "rap espanol",
    "irish rock",
    "french rock",
    "panamanian pop",
    "pagode novo",
    "rumba",
    "r&b en espanol",
    "etherpop",
    "bachata dominicana",
    "punk blues",
    "bubblegrunge",
    "deep new americana",
    "hyperpop",
    "swedish electropop",
    "sheffield indie",
    "german underground rap",
    "tejano",
    "post-punk",
    "cool jazz",
    "complextro",
    "pop emo",
    "polish pop",
    "double drumming",
    "swing",
    "canadian trap",
    "german metal",
    "dreamo",
    "indonesian indie",
    "cumbia sonidera",
    "anime score",
    "spanish rock",
    "jam band",
    "background piano",
    "meditation",
    "swedish trap pop",
    "groove metal",
    "german drill",
    "wrestling",
    "belgian edm",
    "canadian singer-songwriter",
    "brooklyn indie",
    "k-rap",
    "norwegian indie",
    "lullaby",
    "french indietronica",
    "afro dancehall",
    "uk drill",
    "turkish folk",
    "big beat",
    "movie tunes",
    "bow pop",
    "scandipop",
    "vocal house",
    "bass house",
    "classic canadian rock",
    "russian alt pop",
    "white noise",
    "japanese r&b",
    "country rap",
    "electro",
    "classic bollywood",
    "jazz pop",
    "environmental",
    "pop house",
    "uk alternative pop",
    "uk alternative hip hop",
    "uk metalcore",
    "jazz fusion",
    "cumbia 420",
    "drill",
    "traprun",
    "cantopop",
    "neon pop punk",
    "jazz blues",
    "schlager",
    "trap boricua",
    "classic swedish pop",
    "pop reggaeton",
    "aussietronica",
    "afro r&b",
    "christian pop",
    "melbourne bounce international",
    "russian rock",
    "bedroom soul",
    "alternative country",
    "calming instrumental",
    "shoegaze",
    "arabesk",
    "tech house",
    "kentucky hip hop",
    "brazilian reggae",
    "japanese singer-songwriter",
    "oklahoma country",
    "polish alternative rap",
    "ska",
    "contemporary vocal jazz",
    "electro latino",
    "minimal techno",
    "power pop",
    "pop peruano",
    "broadway",
    "flamenco urbano",
    "neo-synthpop",
    "modern blues",
    "oakland hip hop",
    "alternative emo",
    "blues",
    "turkish alt pop",
    "uk post-punk",
    "drum and bass",
    "japanese alternative rock",
    "nyc pop",
    "salsa puertorriquena",
    "classic country pop",
    "lo-fi cover",
    "industrial",
    "indie surf",
    "lo-fi chill",
    "vallenato",
    "eurovision",
    "dutch house",
    "modern hard rock",
    "german alternative rap",
    "new age",
    "london rap",
    "modern folk rock",
    "hamburg hip hop",
    "funk bh",
    "indie electropop",
    "moombahton",
    "canadian indie",
    "anti-folk",
    "golden age hip hop",
    "indie jazz",
    "minnesota hip hop",
    "protopunk",
    "deep underground hip hop",
    "rap dominicano",
    "memphis soul",
    "ninja",
    "modern reggae",
    "post-hardcore",
    "early music",
    "finnish dance pop",
    "reggae en espanol",
    "azontobeats",
    "nigerian hip hop",
    "chilean rock",
    "drill espanol",
    "thai pop",
    "german cloud rap",
    "celtic rock",
    "baroque",
    "german indie",
    "pinoy rock",
    "japanese chillhop",
    "modern alternative pop",
    "deep euro house",
    "nu disco",
    "irish pop",
    "afroswing",
    "pop rock brasileiro",
    "canadian metal",
    "progressive metal",
    "world",
    "acoustic cover",
    "uplifting trance",
    "j-pixie",
    "turkish jazz",
    "focus",
    "classic j-pop",
    "crunk",
    "weirdcore",
    "rawstyle",
    "cumbia",
    "indonesian pop rock",
    "uk funky",
    "pop lgbtq+ brasileira",
    "soul jazz",
    "old school hip hop",
    "irish singer-songwriter",
    "smooth jazz",
    "funk viral",
    "neo classical metal",
    "progressive bluegrass",
    "dubstep",
    "romanian pop",
    "oxford indie",
    "frauenrap",
    "early romantic era",
    "rap napoletano",
    "ska punk",
    "czsk hip hop",
    "finnish pop",
    "speedrun",
    "argentine indie",
    "lo-fi indie",
    "chicago drill",
    "turbo folk",
    "classical era",
    "noise pop",
    "australian psych",
    "neue deutsche harte",
    "pop romantico",
    "political hip hop",
    "canadian electronic",
    "soul blues",
    "arkansas country",
    "japanese vgm",
    "acid rock",
    "antiviral pop",
    "anthem emo",
    "australian electropop",
    "progressive trance",
    "pacific islands pop",
    "coverchill",
    "cumbia chilena",
    "nu-cumbia",
    "j-rap",
    "swedish gangsta rap",
    "gymcore",
    "preschool children's music",
    "melodic metal",
    "phonk",
    "symphonic metal",
    "italian underground hip hop",
    "late romantic era",
    "turkish alternative rock",
    "dance-punk",
    "speed metal",
    "death metal",
    "rome indie",
    "pop rap brasileiro",
    "modern salsa",
    "post-punk argentina",
    "r&b brasileiro",
    "swamp rock",
    "deep turkish pop",
    "dub",
    "danish hip hop",
    "nashville sound",
    "swedish idol pop",
    "israeli pop",
    "british blues",
    "swedish alternative rock",
    "reggae rock",
    "trova",
    "hard bop",
    "swedish metal",
    "venezuelan hip hop",
    "funk pop",
    "polish alternative",
    "chicano rap",
    "lo-fi rap",
    "indie triste",
    "torch song",
    "sertanejo tradicional",
    "christian hip hop",
    "vocaloid",
    "bebop",
    "lovers rock",
    "dancefloor dnb",
    "chamber psych",
    "disney",
    "british singer-songwriter",
    "spanish indie pop",
    "stoner rock",
    "epicore",
    "nederpop",
    "funk consciente",
    "belgian hip hop",
    "dangdut",
    "post-romantic era",
    "anime lo-fi",
    "electra",
    "trancecore",
    "hardcore punk",
    "russian dance",
    "classic schlager",
    "tagalog rap",
    "dembow",
    "microhouse",
    "classic hardstyle",
    "new jersey rap",
    "french reggae",
    "west coast trap",
    "chill pop",
    "nouvelle chanson francaise",
    "albanian hip hop",
    "celtic",
    "visual kei",
    "cartoon",
    "indie game soundtrack",
    "musica de fondo",
    "finnish hip hop",
    "ambient",
    "danspunk",
    "sunshine pop",
    "new york drill",
    "nwobhm",
    "pop nacional antigas",
    "k-indie",
    "piseiro",
    "suomi rock",
    "trap mexicano",
    "zolo",
    "kindermusik",
    "v-pop",
    "experimental pop",
    "birmingham metal",
    "supergroup",
    "australian alternative rock",
    "classify",
    "basshall",
    "greek pop",
    "pagode baiano",
    "gothic metal",
    "euphoric hardstyle",
    "musica para ninos",
    "canadian punk",
    "hi-nrg",
    "south carolina hip hop",
    "ambient worship",
    "melodic dubstep",
    "melodic hardcore",
    "german soundtrack",
    "jawaiian",
    "belgian pop",
    "rebel blues",
    "operatic pop",
    "reading",
    "indie punk",
    "modern power pop",
    "cuarteto",
    "dark clubbing",
    "latin talent show",
    "modern dream pop",
    "pinoy hip hop",
    "boston hip hop",
    "hawaiian hip hop",
    "latin jazz",
    "rkt",
    "swedish trap",
    "vancouver indie",
    "detroit trap",
    "swedish synthpop",
    "rap belge",
    "anadolu rock",
    "japanese soundtrack",
    "christian indie",
    "scottish rock",
    "iskelma",
    "turntablism",
    "melodic death metal",
    "organic house",
    "indian instrumental",
    "alabama rap",
    "german baroque",
    "champeta",
    "russian dance pop",
    "r&b italiano",
    "canadian country",
    "piano cover",
    "south african pop",
    "azonto",
    "spanish new wave",
    "shamanic",
    "turkish singer-songwriter",
    "classic russian rock",
    "deathcore",
    "folklore argentino",
    "arab pop",
    "background jazz",
    "argentine reggae",
    "trap carioca",
    "doo-wop",
    "canadian contemporary country",
    "diva house",
    "pub rock",
    "french synthpop",
    "asmr",
    "jazz trumpet",
    "gospel",
    "rock cristiano",
    "uk americana",
    "ska mexicano",
    "detroit rock",
    "chillstep",
    "chicago indie",
    "dinner jazz",
    "italo dance",
    "classic mandopop",
    "philly indie",
    "folk brasileiro",
    "chinese indie",
    "boom bap espanol",
    "chinese viral pop",
    "tecnobanda",
    "experimental",
    "milan indie",
    "jazz rap",
    "intelligent dance music",
    "hard rock brasileiro",
    "dutch trance",
    "forro de favela",
    "british soundtrack",
    "deep ccm",
    "st louis rap",
    "northern soul",
    "rap chileno",
    "norteno-sax",
    "comic metal",
    "argentine telepop",
    "classic soundtrack",
    "bossa nova cover",
    "hyphy",
    "roots worship",
    "salsa colombiana",
    "stoner metal",
    "hands up",
    "swedish indie pop",
    "velha guarda",
    "carnaval",
    "big band",
    "cumbia ranchera",
    "albanian pop",
    "english indie rock",
    "tekk",
    "boston rock",
    "trap chileno",
    "japanese emo",
    "cubaton",
    "drill francais",
    "concurso de talentos argentino",
    "russian drain",
    "musica infantil",
    "classic opm",
    "russian drill",
    "levenslied",
    "future house",
    "malaysian pop",
    "water",
    "german romanticism",
    "ambient pop",
    "rap mineiro",
    "philly soul",
    "vegas indie",
    "float house",
    "indonesian jazz",
    "mainland chinese pop",
    "sacramento indie",
    "synthwave",
    "melbourne bounce",
    "boom bap",
    "old school rap francais",
    "minneapolis sound",
    "chilean indie",
    "stride",
    "russian emo rap",
    "rock urbano mexicano",
    "psychedelic hip hop",
    "seattle hip hop",
    "canadian pop punk",
    "rock steady",
    "manguebeat",
    "jazz boom bap",
    "bmore",
    "classic uk pop",
    "rhythm and blues",
    "modern southern rock",
    "jazz saxophone",
    "tropicalia",
    "rock drums",
    "kentucky roots",
    "russian gangster rap",
    "hardcore techno",
    "gothic symphonic metal",
    "ukrainian pop",
    "cancion infantil latinoamericana",
    "small room",
    "rock alternativo brasileiro",
    "stomp pop",
    "russelater",
    "neo-singer-songwriter",
    "new age piano",
    "italian disco",
    "korean ost",
    "alternative pop rock",
    "christian relaxative",
    "jazz piano",
    "sound",
    "instrumental rock",
    "rap sardegna",
    "j-division",
    "roots americana",
    "portuguese pop",
    "pop electronico",
    "new jersey indie",
    "chicago bop",
    "british folk",
    "pinoy indie",
    "sleaze rock",
    "g-house",
    "laiko",
    "cumbia peruana",
    "rock gospel brasileiro",
    "brighton indie",
    "indie hip hop",
    "fnf",
    "ambient folk",
    "swedish pop rap",
    "classic pakistani pop",
    "flamenco",
    "rap cristiano",
    "afrofuturismo brasileiro",
    "traditional blues",
    "musica popular colombiana",
    "pet calming",
    "taiwan singer-songwriter",
    "australian reggae fusion",
    "aussie drill",
    "red dirt",
    "rap df",
    "surf punk",
    "edmonton indie",
    "rai",
    "happy hardcore",
    "karadeniz turkuleri",
    "middle earth",
    "progressive post-hardcore",
    "czech rock",
    "indian indie",
    "australian indie folk",
    "funk mandelao",
    "australian country",
    "latin metal",
    "finnish metal",
    "german hard rock",
    "contemporary jazz",
    "mexican rock-and-roll",
    "future garage",
    "russian punk",
    "post-rock",
    "electro swing",
    "djent",
    "electropowerpop",
    "lagu jawa",
    "j-metal",
    "rif",
    "hopebeat",
    "variete francaise",
    "eau claire indie",
    "j-acoustic",
    "women's music",
    "garage psych",
    "japanese electropop",
    "electronic rock",
    "singaporean pop",
    "latin afrobeat",
    "swedish tropical house",
    "colombian hip hop",
    "trap baiano",
    "medieval folk",
    "afrobeat",
    "swedish power metal",
    "turkish alternative",
    "lo-fi",
    "impressionism",
    "modern funk",
    "austindie",
    "banda jalisciense",
    "el paso indie",
    "synth funk",
    "musica catalana",
    "liedermacher",
    "greek trap",
    "salsa international",
    "german punk",
    "reggaeton chileno",
    "british indie rock",
    "banda caliente",
    "jazztronica",
    "baltimore indie",
    "slayer",
    "duranguense",
    "desi trap",
    "cyberpunk",
    "canzone d'autore",
    "bolero mexicano",
    "afro soul",
    "pop virale italiano",
    "rap cearense",
    "j-pop boy group",
    "christian trap",
    "belgian dance",
    "spanish punk",
    "oakland indie",
    "german house",
    "livetronica",
    "jazz cover",
    "organic electronic",
    "turkce drill",
    "swedish singer-songwriter",
    "arabic hip hop",
    "wonky",
    "asian american hip hop",
    "art punk",
    "kazakh pop",
    "rhode island rap",
    "solo wave",
    "tollywood",
    "persian pop",
    "athens indie",
    "swedish drill",
    "cosmic american",
    "kazakh hip hop",
    "nerdcore brasileiro",
    "future funk",
    "kirtan",
    "bronx hip hop",
    "folk punk",
    "teen pop",
    "experimental hip hop",
    "hindi hip hop",
    "javanese dangdut",
    "classic girl group",
    "drill brasileiro",
    "classic cantopop",
    "neoclassical darkwave",
    "ecuadorian pop",
    "indie quebecois",
    "anime rap",
    "wave",
    "canadian latin",
    "classic danish pop",
    "danish rock",
    "rap underground espanol",
    "dutch indie",
    "disney horspiele",
    "trap venezolano",
    "trap dominicano",
    "comedy",
    "german reggae",
    "sky room",
    "barnmusik",
    "trap funk",
    "bases de freestyle",
    "garage rock revival",
    "dangdut koplo",
    "psychedelic soul",
    "classic russian pop",
    "classic indo pop",
    "norwegian pop rap",
    "bluegrass",
    "chicha",
    "channel pop",
    "medieval rock",
    "tamil hip hop",
    "nu-metalcore",
    "jazz guitar",
    "rap maroc",
    "banda carnavalera",
    "russian post-punk",
    "j-idol",
    "j-pop girl group",
    "moroccan pop",
    "glee club",
    "danish electronic",
    "central asian hip hop",
    "australian garage punk",
    "ottawa rap",
    "musica triste brasileira",
    "rap inde",
    "rave funk",
    "indian singer-songwriter",
    "classic norwegian pop",
    "harlem renaissance",
    "rap underground mexicano",
    "hamburg electronic",
    "kentucky indie",
    "russian ccm",
    "a cappella",
    "polish classical",
    "fourth world",
    "chicago punk",
    "electro-pop francais",
    "russian rave",
    "dansband",
    "rock uruguayo",
    "indonesian folk pop",
    "mississippi hip hop",
    "uptempo hardcore",
    "rap geek",
    "german singer-songwriter",
    "kosovan pop",
    "cumbia santafesina",
    "german trance",
    "breakbeat",
    "uk doom metal",
    "czech hip hop",
    "bc underground hip hop",
    "indonesian viral pop",
    "deep disco house",
    "musica tradicional cubana",
    "liquid funk",
    "electronica argentina",
    "ethnotronica",
    "uk dnb",
    "idol rock",
    "icelandic indie",
    "nashville singer-songwriter",
    "turkish deep house",
    "portland hip hop",
    "greek hip hop",
    "spanish metal",
    "nu gaze",
    "russian electronic",
    "australian house",
    "slowcore",
    "indonesian rock",
    "hip hop tuga",
    "ye ye",
    "welsh rock",
    "taiwan indie",
    "czech pop",
    "vallenato moderno",
    "uk dancehall",
    "canadian electropop",
    "minimal tech house",
    "ghazal",
    "german power metal",
    "groove room",
    "classic indonesian rock",
    "study beats",
    "trap pesado",
    "instrumental funk",
    "chill guitar",
    "melodic thrash",
    "retro soul",
    "liverpool indie",
    "norwegian rock",
    "mollywood",
    "tex-mex",
    "danish metal",
    "slowed and reverb",
    "uk reggae",
    "rap baiano",
    "soca",
    "early modern classical",
    "brazilian ccm",
    "rap algerien",
    "brega funk",
    "peruvian rock",
    "christian metal",
    "pakistani hip hop",
    "swedish melodeath",
    "nz reggae",
    "alternative pop",
    "folktronica",
    "fotbollslatar",
    "bhangra",
    "russian grime",
    "chicago soul",
    "vapor pop",
    "german alternative rock",
    "gaming dubstep",
    "brazilian indie",
    "finnish power metal",
    "australian talent show",
    "comedy rap",
    "transpop",
    "pinoy r&b",
    "uk house",
    "south african rock",
    "pakistani pop",
    "japanese classical",
    "seattle indie",
    "pop violin",
    "egyptian pop",
    "reggaeton mexicano",
    "healing",
    "rock brasiliense",
    "virginia hip hop",
    "irish folk",
    "psychedelic trance",
    "rap canario",
    "indonesian r&b",
    "german pop rock",
    "shibuya-kei",
    "instrumental grime",
    "harlem hip hop",
    "grave wave",
    "punjabi hip hop",
    "japanese soul",
    "austropop",
    "binaural",
    "thai indie pop",
    "icelandic pop",
    "chutney",
    "drone",
    "haryanvi pop",
    "discofox",
    "antideutsche",
    "rap tunisien",
    "chillsynth",
    "scottish singer-songwriter",
    "swiss indie",
    "zhongguo feng",
    "french soundtrack",
    "bubble trance",
    "rock gaucho",
    "brazilian jazz",
    "israeli mediterranean",
    "folk metal",
    "italian pop rock",
    "icelandic rock",
    "merengue",
    "contemporary post-bop",
    "volksmusik",
    "australian trap",
    "japanese instrumental",
    "palm desert scene",
    "chicago hardcore",
    "south african alternative",
    "australian children's music",
    "salsa peruana",
    "colombian rock",
    "belgian rock",
    "australian metalcore",
    "upstate ny rap",
    "turkish psych",
    "pinoy reggae",
    "italian baroque",
    "funk das antigas",
    "kawaii future bass",
    "russian indie",
    "australian alternative pop",
    "old school dancehall",
    "canzone napoletana",
    "hardstyle",
    "russian romanticism",
    "black metal",
    "progressive metalcore",
    "morelos indie",
    "boogaloo",
    "swedish death metal",
    "scream rap",
    "shush",
    "deep pop edm",
    "music box",
    "swedish soul",
    "classic city pop",
    "violao",
    "r&b argentino",
    "gujarati pop",
    "gothenburg indie",
    "indonesian folk",
    "samba moderno",
    "chihuahua indie",
    "scottish new wave",
    "singaporean mandopop",
    "nashville hip hop",
    "kiwi rock",
    "indian edm",
    "kavkaz",
    "israeli rock",
    "nursery",
    "funk 150 bpm",
    "space rock",
    "salsa venezolana",
    "okinawan pop",
    "classic israeli pop",
    "folk rock italiano",
    "quebec indie",
    "bass music",
    "swedish indie rock",
    "samba de roda",
    "turkish edm",
    "russian edm",
    "guadalajara indie",
    "rock kapak",
    "jovem guarda",
    "alternative americana",
    "minecraft",
    "dark wave",
    "nordic house",
    "japanese trap",
    "rave",
    "danish pop rock",
    "belarusian hip hop",
    "pinoy trap",
    "canadian ccm",
    "new orleans jazz",
    "opera metal",
    "cumbia paraguaya",
    "canadian soundtrack",
    "swedish indie folk",
    "ska revival",
    "pop folk",
    "turkce slow sarkilar",
    "veracruz indie",
    "japanese punk rock",
    "mexican classic rock",
    "italian alternative",
    "hungarian pop",
    "czech folk",
    "shanty",
    "scottish indie",
    "future rock",
    "swedish jazz",
    "noise rock",
    "neo r&b",
    "horror punk",
    "alte",
    "jump up",
    "ectofolk",
    "bergen indie",
    "lithuanian electronic",
    "manchester hip hop",
    "cumbia sonorense",
    "hindi indie",
    "progressive groove metal",
    "glitch hop",
    "kansas city hip hop",
    "swedish hard rock",
    "chill out",
    "indonesian worship",
    "rock mineiro",
    "washington indie",
    "reggaeton cristiano",
    "french shoegaze",
    "korean instrumental",
    "indie catala",
    "indonesian pop punk",
    "boom bap brasileiro",
    "rune folk",
    "german r&b",
    "christlicher rap",
    "funky tech house",
    "ann arbor indie",
    "umbanda",
    "funky house",
    "bay area indie",
    "ethereal wave",
    "chilena",
    "musica gaucha tradicionalista",
    "midwest emo",
    "world fusion",
    "smooth saxophone",
    "anime piano",
    "brutal death metal",
    "nuevo flamenco",
    "lebanese pop",
    "indonesian hip hop",
    "punk urbano",
    "native american",
    "british alternative rock",
    "celtic metal",
    "classic turkish pop",
    "texas pop punk",
    "pianissimo",
    "austrian pop",
    "dutch cabaret",
    "world meditation",
    "pop quebecois",
    "mariachi cristiano",
    "city pop",
    "indonesian lo-fi pop",
    "kollywood",
    "saskatchewan indie",
    "musica costena",
    "early us punk",
    "tamaulipas rap",
    "argentine alternative rock",
    "scam rap",
    "russian punk rock",
    "classic garage rock",
    "post-minimalism",
    "birmingham grime",
    "sacramento hip hop",
    "canadian americana",
    "lithuanian edm",
    "south african house",
    "filthstep",
    "idol",
    "taiwan hip hop",
    "barnsagor",
    "glitch",
    "buffalo hip hop",
    "russian metal",
    "polish rock",
    "celtic punk",
    "musica andina",
    "free jazz",
    "indonesian alternative rock",
    "classic house",
    "underground rap",
    "rock andaluz",
    "nottingham indie",
    "christian metalcore",
    "mexican pop punk",
    "acoustic rock",
    "kabarett",
    "zouk riddim",
    "singaporean singer-songwriter",
    "destroy techno",
    "abstract hip hop",
    "chamame",
    "hip hop quebecois",
    "kayokyoku",
    "jangle pop",
    "viking metal",
    "pop chileno",
    "texas blues",
    "deep southern trap",
    "welsh metal",
    "nintendocore",
    "puerto rican rock",
    "riot grrrl",
    "indie rock mexicano",
    "nova musica pernambucana",
    "banjo",
    "belgian indie",
    "atmosphere",
    "scandinavian r&b",
    "cumbia del sureste",
    "parody",
    "norwegian hip hop",
    "lo-fi emo",
    "doom metal",
    "batidao romantico",
    "brazilian punk",
    "gothic rock",
    "electro jazz",
    "psychedelic doom",
    "brazilian bass",
    "french romanticism",
    "russian underground rap",
    "acoustic chill",
    "oyun havasi",
    "romanian house",
    "gothenburg metal",
    "hungarian rock",
    "ska chileno",
    "new comedy",
    "bergamo indie",
    "hard bass",
    "afro house",
    "north carolina roots",
    "lo-fi vgm",
    "jazz trio",
    "classic polish pop",
    "final fantasy",
    "electroclash",
    "nottingham hip hop",
    "piano blues",
    "musica aragonesa",
    "deconstructed club",
    "tribal house",
    "thai indie rock",
    "techno",
    "manele",
    "sound team",
    "vietnamese hip hop",
    "gospel r&b",
    "dixieland",
    "italian romanticism",
    "chill beats",
    "rap lyonnais",
    "children's folk",
    "viking folk",
    "darksynth",
    "bitpop",
    "lds youth",
    "auckland indie",
    "karadeniz pop",
    "vaporwave",
    "steampunk",
    "canadian folk",
    "yugoslav rock",
    "tropical alternativo",
    "battle rap",
    "experimental rock",
    "swiss pop",
    "stomp and flutter",
    "bboy",
    "easycore",
    "rap baixada fluminense",
    "dark techno",
    "minimalism",
    "icelandic classical",
    "afghan pop",
    "ghanaian hip hop",
    "ecm-style jazz",
    "indiana hip hop",
    "narodna muzika",
    "danseband",
    "chicago blues",
    "ebm",
    "ukg revival",
    "magyar alternative",
    "french jazz",
    "texas metal",
    "chill lounge",
    "german metalcore",
    "drill italiana",
    "swedish country",
    "romantico",
    "gabba",
    "texas latin rap",
    "deep latin christian",
    "chinese idol pop",
    "bassline",
    "nederlandse hardstyle",
    "neue deutsche welle",
    "italian opera",
    "northern irish indie",
    "disco polo",
    "kurdish pop",
    "japanese pop rap",
    "volkspop",
    "uk pop punk",
    "samba-rock",
    "spanish folk metal",
    "technical death metal",
    "classic iskelma",
    "deutschrock",
    "electro-industrial",
    "sludge metal",
    "melanesian pop",
    "classic belgian pop",
    "chiptune",
    "east coast reggae",
    "melodic techno",
    "japanese vtuber",
    "oc rap",
    "swancore",
    "classic colombian pop",
    "latin viral rap",
    "nightrun",
    "emo rap italiano",
    "freestyle",
    "modern ska punk",
    "thai rock",
    "louvor",
    "guaracha",
    "nashville indie",
    "lesen",
    "greek drill",
    "kizomba",
    "classic malaysian pop",
    "vintage italian soundtrack",
    "asbury park indie",
    "soulful house",
    "mizrahi",
    "australian r&b",
    "dutch metal",
    "classic finnish pop",
    "classic arab pop",
    "dark post-punk",
    "cologne hip hop",
    "chicago house",
    "chinese r&b",
    "lo-fi house",
    "trap antillais",
    "italian reggae",
    "classic finnish rock",
    "new jersey hardcore",
    "khaliji",
    "indian lo-fi",
    "mambo",
    "frenchcore",
    "acoustic punk",
    "samba-jazz",
    "belly dance",
    "uk garage",
    "samba reggae",
    "reggae tuga",
    "naija worship",
    "australian underground hip hop",
    "country gospel",
    "progressive psytrance",
    "swedish americana",
    "post-doom metal",
    "latin classical",
    "ghanaian pop",
    "acoustic blues",
    "tecnobrega",
    "turkce kadin rap",
    "spanish modern rock",
    "contemporary gospel",
    "russian folk rock",
    "metallic hardcore",
    "tagalog worship",
    "rock independant francais",
    "cowboy western",
    "jungle",
    "nordic soundtrack",
    "dark disco",
    "arab trap",
    "mexican edm",
    "italian lounge",
    "ukrainian rock",
    "minneapolis indie",
    "musica para criancas",
    "balkan hip hop",
    "indie viet",
    "turkish instrumental",
    "muziek voor kinderen",
    "orgcore",
    "punk 'n' roll",
    "dansktop",
    "theme",
    "egyptian hip hop",
    "jewish pop",
    "swedish reggae",
    "gbvfi",
    "portland indie",
    "italian soundtrack",
    "hawaiian",
    "uzbek pop",
    "acoustic opm",
    "popping",
    "japanese alternative pop",
    "swedish melodic rock",
    "partido alto",
    "christmas instrumental",
    "american folk revival",
    "cueca chilena",
    "chinese singer-songwriter",
    "russian alternative rock",
    "alabama indie",
    "hard alternative",
    "swedish eurodance",
    "latintronica",
    "irish hip hop",
    "japanese pop punk",
    "argentine punk",
    "barnemusikk",
    "bakersfield sound",
    "png pop",
    "new tribe",
    "mathcore",
    "experimental r&b",
    "new weird america",
    "australian singer-songwriter",
    "amapiano",
    "ambeat",
    "circuit",
    "swedish dancehall",
    "country blues",
    "folclore salteno",
    "trance brasileiro",
    "classic thai pop",
    "north east england indie",
    "polish indie",
    "irish country",
    "hurdy-gurdy",
    "idol kayo",
    "japanese old school hip hop",
    "rap boricua",
    "bulgarian pop",
    "afrikaans",
    "viral trap",
    "russian viral rap",
    "toronto indie",
    "post-metal",
    "croatian pop",
    "cello",
    "latinx alternative",
    "hardcore",
    "denpa-kei",
    "neomelodici",
    "estonian hip hop",
    "thai hip hop",
    "world devotional",
    "laboratorio",
    "classic dubstep",
    "monterrey indie",
    "progressive deathcore",
    "norwegian country",
    "romanian trap",
    "louisiana blues",
    "bandinhas",
    "arab electronic",
    "indonesian city pop",
    "belarusian indie",
    "latin funk",
    "musique pour enfants",
    "glam punk",
    "korean city pop",
    "classic peruvian pop",
    "malaysian mandopop",
    "venezuelan rock",
    "progressive jazz fusion",
    "groove gospel",
    "instrumental post-rock",
    "surf music",
    "leicester indie",
    "uk contemporary jazz",
    "lo-fi brasileiro",
    "modern jazz piano",
    "popwave",
    "brain waves",
    "seiyu",
    "dutch drill",
    "outsider house",
    "colombian indie",
    "malaysian indie",
    "norwegian metal",
    "carnaval cadiz",
    "oldschool deutschrap",
    "samba paulista",
    "argentine heavy metal",
    "concepcion indie",
    "fingerstyle",
    "neo-progressive",
    "huzunlu sarkilar",
    "brega romantico",
    "israeli hip hop",
    "vocal harmony group",
    "old-time",
    "reggae cover",
    "spanish noise pop",
    "papuri",
    "peruvian hip hop",
    "digital hardcore",
    "classical tenor",
    "new jersey underground rap",
    "japanese jazz",
    "dakke dak",
    "indie liguria",
    "high-tech minimal",
    "rock baiano",
    "german viral rap",
    "neoclassicism",
    "mande pop",
    "zouk",
    "gospel antigas",
    "scottish indie rock",
    "entehno",
    "japanese post-hardcore",
    "bouncy house",
    "mambo chileno",
    "canadian old school hip hop",
    "rap antillais",
    "nz hip hop",
    "synthesizer",
    "finnish alternative rock",
    "pittsburgh indie",
    "shred",
    "latincore",
    "new jersey punk",
    "japanese jazz fusion",
    "finnish melodeath",
    "italian tenor",
    "perth indie",
    "german oi",
    "indie rockism",
    "industrial hip hop",
    "south african hip hop",
    "nightcore",
    "newcastle nsw indie",
    "emo mexicano",
    "flamenco fusion",
    "progressive uplifting trance",
    "boston indie",
    "russian viral pop",
    "austin americana",
    "brit funk",
    "kawaii metal",
    "chinese drama ost",
    "jamgrass",
    "avant-garde jazz",
    "diy emo",
    "strut",
    "hololive",
    "french metal",
    "contemporary classical",
    "german indie folk",
    "dong-yo",
    "deep tech house",
    "symphonic deathcore",
    "finnish heavy metal",
    "rap nacional antigo",
    "melodic power metal",
    "icelandic experimental",
    "straight edge",
    "rock catala",
    "fado",
    "vgm remix",
    "swiss hip hop",
    "belo horizonte indie",
    "punk rock mexicano",
    "slc indie",
    "south african pop dance",
    "australian indie rock",
    "indian folk",
    "west coast reggae",
    "dark rock",
    "russian chanson",
    "k-rock",
    "russian reggae",
    "uk tech house",
    "dangdut remix",
    "honky tonk",
    "flute rock",
    "reggae cristao",
    "lithuanian pop",
    "sholawat",
    "rap catala",
    "alberta country",
    "birmingham hip hop",
    "comedy rock",
    "norwegian singer-songwriter",
    "oktoberfest",
    "chinese hip hop",
    "hungarian hip hop",
    "atlanta metal",
    "christian punk",
    "israeli singer-songwriter",
    "gypsy jazz",
    "early avant garde",
    "j-indie",
    "manchester indie",
    "vbs",
    "chanson virale",
    "boston punk",
    "brazilian soul",
    "rap montrealais",
    "psychedelic pop",
    "pirate",
    "riddim",
    "canadian metalcore",
    "british power metal",
    "uk experimental electronic",
    "brazilian house",
    "slamming deathcore",
    "kindie rock",
    "instrumental soul",
    "turkish soundtrack",
    "polish alternative rock",
    "moldovan pop",
    "czech pop rock",
    "souldies",
    "voetbal",
    "military rap",
    "acoustic guitar cover",
    "retro metal",
    "russian ska",
    "chilean hardcore",
    "russian indie rock",
    "relaxative",
    "slovak pop",
    "canadian classical",
    "african rock",
    "indonesian reggae",
    "san diego rap",
    "psicodelia brasileira",
    "rap feminino nacional",
    "swedish garage rock",
    "bandung indie",
    "sudanese pop",
    "finnish death metal",
    "slovak hip hop",
    "experimental ambient",
    "cologne indie",
    "north carolina indie",
    "deep norteno",
    "shonen",
    "nuevo folklore mexicano",
    "musica canaria",
    "reggae gaucho",
    "rap anime",
    "new orleans blues",
    "romanian rap",
    "delta blues",
    "ukrainian indie",
    "rap uruguayo",
    "traditional country",
    "deep talent show",
    "west end",
    "futurepop",
    "boston metal",
    "pop teen brasileiro",
    "vintage chinese pop",
    "qawwali",
    "belarusian pop",
    "brisbane indie",
    "rock quebecois",
    "acid house",
    "australian indigenous",
    "rock alternativo espanol",
    "yaoi",
    "deep minimal techno",
    "hip-hop experimental",
    "psychill",
    "oi",
    "skansk musik",
    "indie dream pop",
    "balkan beats",
    "ballet class",
    "garage pop",
    "tango",
    "cumbia lagunera",
    "roda de samba",
    "drift",
    "cancion infantil mexicana",
    "albuquerque indie",
    "classical performance",
    "futuristic swag",
    "power-pop punk",
    "virginia metal",
    "japanese new wave",
    "pinoy pop punk",
    "classic j-rock",
    "mundart",
    "cumbia colombiana regia",
    "japanese dance pop",
    "suomirap",
    "french folk pop",
    "kingston on indie",
    "polish reggae",
    "musica per bambini",
    "san diego indie",
    "quran",
    "vintage french electronic",
    "bhajan",
    "trap colombiano",
    "sevdah",
    "finnish edm",
    "alternative roots rock",
    "brazilian metal",
    "eurobeat",
    "trap metal italiana",
    "pony",
    "psychobilly",
    "messianic praise",
    "san marcos tx indie",
    "canadian children's music",
    "symphonic black metal",
    "rap cristao",
    "appalachian folk",
    "korean old school hip hop",
    "canadian celtic",
    "brazilian emo",
    "rap romantico",
    "classic praise",
    "boston folk",
    "space age pop",
    "adoracion",
    "south carolina indie",
    "ambient house",
    "swiss rock",
    "spanish synthpop",
    "french opera",
    "indie extremena",
    "melodic groove metal",
    "canadian post-hardcore",
    "tempe indie",
    "german ska",
    "ballroom",
    "brazilian boogie",
    "freakbeat",
    "english baroque",
    "neurofunk",
    "nasheed",
  ],
};
